const api = "http://localhost:4000/api/v1";

const citiesAvailable = [
    "ATLANTA",
    "BALTIMORE",
    "BIRMINGHAM",
    "BOSTON",
    "BUFFALO",
    "CHARLOTTE",
    "CHICAGO",
    "CINCINNATI",
    "CLEVELAND",
    "COLUMBUS",
    "DALLAS",
    "DENVER",
    "DETROIT",
    "FORTWORTH",
    "HARTFORD",
    "HOUSTON",
    "INDIANAPOLIS",
    "KANSASCITY",
    "LOSANGELES",
    "MEMPHIS",
    "MIAMI",
    "MILWAUKEE",
    "MINNEAPOLISSTPAUL",
    "NEWORLEANS",
    "NEWYORK",
    "NORFOLK",
    "OAKLAND",
    "OKLAHOMACITY",
    "PHILADELPHIA",
    "PHOENIX",
    "PITTSBURGH",
    "PORTLAND",
    "PROVIDENCE",
    "ROCHESTER",
    "SACRAMENTO",
    "SALTLAKECITY",
    "SANANTONIO",
    "SANBERNADINO",
    "SANDIEGO",
    "SANFRANCISCO",
    "SANJOSE",
    "SANTAANA",
    "SEATTLE",
    "STLOUIS",
    "TAMPA",
    "WASHINGTONDC"
];

export {api, citiesAvailable};